### ISSUE TITLE
Add pre-filled `UnitConverter`

### ISSUE THREAD

**Issue by nathan-hess** [nathan-hess/python-utilities#30]
**Issue**
There are units (meters, inches, seconds, etc.) that are extremely common, so it would be convenient if there were a pre-filled unit converter that contained these units so that users don't need to repeatedly define them.

**Possible Solutions**
Create a new class, derived from `UnitConverter`, that is initialized with a variety of common units.

**Task List**
- [x] Create pre-filled unit converter
- [x] Add common units to pre-filled unit converter
- [x] Add documentation page listing units in pre-filled unit converter

**Additional Notes**
- General
  - https://www.engineeringtoolbox.com/si-unit-system-d_30.html
- Computer storage
  - https://www.ibm.com/docs/en/storage-insights?topic=overview-units-measurement-storage-data
  - https://www.engineeringtoolbox.com/megabytes-kilobytes-bytes-d_2203.html
