### ISSUE TITLE
Create unit converter CLI

### ISSUE THREAD

**Issue by nathan-hess** [nathan-hess/python-utilities#31]
**Issue**
For everyday use, it would be helpful to have a unit converter available in a terminal.

**Possible Solutions**
Create a wrapper around the `UnitConverter` class that performs unit conversions in the terminal, using command-line arguments to provide inputs.

**Task List**
- [x] Create wrapper around `UnitConverter` to perform unit conversions.
- [x] Configure build settings to make CLI available after package installation.
- [x] Add documentation example explaining how to use unit converter CLI.

**Additional Notes**
- https://setuptools.pypa.io/en/latest/userguide/entry_point.html
